ItemStocks = {
'stick',                          # Name = Stick
'bow',                            # Name = Bow
'pizza',                          # Name = Pizza
'gravityrod',                     # Name = Gravity Rod
'nuke',                           # Name = Nuke
'singfruit',                      # Name = Singfruit
'whip',                           # Name = Whip
'whoopee',                        # Name = Whoopee Cushion
'selfie',                         # Name = Selfie Stick
'moneybag',                       # Name = Moneybag
'unknownbase',                    # Name = Unknown Item
'hammer',                         # Name = Hammer
'raygun',                         # Name = Ray Gun
'axe',                            # Name = Pumpking's Axe
'cubebrick',                      # Name = Brick Cube
'giftbox',                        # Name = Gift Box
'rock',                           # Name = Rock
'fakecoin',                       # Name = Coin
'backpack',                       # Name = Backpack
'backpack2',                      # Name = Jetpack
'book',                           # Name = Help Book
'wings',                          # Name = Wings
'stilts',                         # Name = Stilts
'badgebase',                      # Name = Base Badge
'sash',                           # Name = Badge Sash
'shield',                         # Name = Shield
'compass',                        # Name = Compass
'shield3',                        # Name = Soul Shield
'shield2',                        # Name = Demon Shield
'boots',                          # Name = Boots
'boots2',                         # Name = Super Boots
'bootsobsidian',                  # Name = Obsidian Boots
'bootsclown',                     # Name = Clown Boots
'bootsfire',                      # Name = Lava Walker Boots
'boots4',                         # Name = Whoopee Boots
'boots3',                         # Name = Spring Boots
'fannypack',                      # Name = Fanny Pack
'book2',                          # Name = Super Book
'lantern2',                       # Name = Blue Fire Spirit
'lantern',                        # Name = Lantern
'bootscoal',                      # Name = Coal Boots
'book3',                          # Name = Charred Book
'boots4super',                    # Name = Super Whoopee Boots
'compassyellow',                  # Name = Yellow Compass
'bootsultra',                     # Name = Ultra Boots
'backpack3',                      # Name = Rocket Pack
'wings2',                         # Name = Flaming Wings
'mechawhip',                      # Name = Mecha Whip
'bootscash',                      # Name = Cashmere's Wear
'passivebase',                    # Name = Actually Nothing
'rope',                           # Name = Rope
'fabric',                         # Name = Fabric
'brokekey2',                      # Name = The Other Half
'brokekey1',                      # Name = Broken Key
'magic',                          # Name = Super Magic
'wood',                           # Name = Wood
'firespirit',                     # Name = Fire Spirit
'goop',                           # Name = Monster Goop
'gizmo',                          # Name = Strange Gizmo
'magicultra',                     # Name = Ultra Magic
'boomerang',                      # Name = Boomerang
'yoyo',                           # Name = Yo-yo
'kart',                           # Name = Kart
'ufo',                            # Name = UFO
'ufo2',                           # Name = Actually Flying Disc
'invisikart',                     # Name = Invisikart
'clowncar',                       # Name = Clown Car
'bubble2',                        # Name = Barnabus
'bubble',                         # Name = Bubble
'horsey',                         # Name = Trusty Steed
'heart',                          # Name = Heart
'key',                            # Name = Key
'coin',                           # Name = Coin
'bomb',                           # Name = Bomb
'arrows',                         # Name = Arrows
'trapbomb',                       # Name = Suspicious Bomb
'coinbonus',
'baseball',                       # Name = Baseball
'whip2',                          # Name = Super Whip
'whoopee2',                       # Name = Super Whoopee Cushion
'dagger',                         # Name = Dagger
'daggerold',                      # Name = CC Dagger
'sword',                          # Name = Sword
'mushhammer',                     # Name = Mush Masher
'hammertrash',                    # Name = Trash Compactor
'flyingdisc',                     # Name = Flying Disc
'twinkle',                        # Name = Twinkle Boomerang
'stardust',                       # Name = Stardust Boomerang
'boomerang2',                     # Name = Super Boomerang
'fungus',                         # Name = Fungus
'hammerarrow',                    # Name = Helpful Arrow
'swordfire',                      # Name = Firebranded Fury
'swordice',                       # Name = Blizzard Blade
'glassdagger',                    # Name = Glass Dagger
'cubecrate',                      # Name = Crate Cube
'swordpizza',                     # Name = Pizza Slicer
'swordshroom',                    # Name = Mushroom Fencing Thing
'raygun2',                        # Name = Cursed Ray Gun
'whoopeeold',                     # Name = Whoopie Cushon
'bruhtton',                       # Name = bruhtton
'coal',                           # Name = Lump of Coal
'chocopizza',                     # Name = Chocolate Pizza
'chocoheart',                     # Name = Chocolate Heart
'plushie',                        # Name = Monster Plushie
'badpizza',                       # Name = Burnt Pizza
'boomerang3',                     # Name = Triple Boomerang
'ultral',                         # Name = The Ultra L
'whipworm',                       # Name = Worm Whip
'poop',                           # Name = Poop
'moneybag2',                      # Name = Moneybag?
'blockrod',                       # Name = Block Rod
'l',                              # Name = The L
'gun',                            # Name = Gum
'smash',                          # Name = Clown License
'potattack',                      # Name = Attack Potion
'potbonus',                       # Name = Bonus Heart Potion
'pothealth',                      # Name = Health Potion
'potjump',                        # Name = Jump Potion
'potlight',                       # Name = Light Potion
'potspeed',                       # Name = Speed Potion
'badgerainy',                     # Name = Rainy Day Badge
'badgeinverted',                  # Name = Inverted Badge
'badgelightning',                 # Name = Lightning Badge
'badgeastronaut',                 # Name = Astronaut Badge
'badgeantidote',                  # Name = Antidote Badge
'badgeglasses',                   # Name = Broken Glasses Badge
'badgefamiliar',                  # Name = Familiar Badge
'badgesquatched',                 # Name = Badge'd Squatch
'badgeflipped',                   # Name = Overturned Badge
'badgesnomang',                   # Name = snomang
'badgebouncy',                    # Name = Bouncy Badge
'badgehitbox',                    # Name = Hitbox Badge
'badgelemon',                     # Name = Lemon Badge
'badgestone',                     # Name = Stone Heart Badge
'badgespeed',                     # Name = Speedy Badge
'badgerevenge',                   # Name = Revenge Badge
'badgewallet',                    # Name = Big wallet Badge
'badgepeekaboo',                  # Name = Peekaboo Badge
'badgenerd',                      # Name = Certified Nerd Badge
'badgeattack',                    # Name = Attack Badge
'badgedetective',                 # Name = Detective Badge
'badgeleftovers',                 # Name = Leftovers Badge
'badgedance',                     # Name = Dance Badge
'badgehomerun',                   # Name = Homerun Badge
'badgefriendship',                # Name = Friendship Badge
'badgecactus',                    # Name = Cactus Badge
'badgebribble',                   # Name = BRIBBLECO Badge
'badgebeebo',                     # Name = Beebo Badge
'badgenuke',                      # Name = Nuke Badge
'badgedarkness',                  # Name = Darkness Badge
'badgeenergetic',                 # Name = Energetic Badge
'badgemarksman',                  # Name = Marksman Badge
'badgeblast',                     # Name = Blast Badge
'badgesevered',                   # Name = Severed Badge
'danceheadtrick',                 # Name = Head Trick
'dancebeebo',                     # Name = The Beebo
'dancebouncy',                    # Name = Bouncin' Around
'dancebryant',                    # Name = Bryant Dance
'dancecaramel',                   # Name = Caramel Dance
'dancechaos',                     # Name = Chaotic Dance
'danceclown',                     # Name = Clown Dance
'danceeddie',                     # Name = Eddie Dance
'dancegrounded',                  # Name = Grounded Dance
'dancewoogie',                    # Name = Boogie Woogie
'dancejazz',                      # Name = Jazzy Dance
'dancekick',                      # Name = Kazotsky Kick
'dancepbj',                       # Name = PBJ Dance
'dancepenguin',                   # Name = Penguin Dance
'dancerobot',                     # Name = The Robot
'danceslowclap',                  # Name = Slow Clap
'dancespin',                      # Name = The Tornado
'dancesunday',                    # Name = when it sunday
'dancetpose',                     # Name = The Big T
'dancetrent',                     # Name = Trent Dance
'dancetruman',                    # Name = Truman Dance
'dancevictory',                   # Name = Victory
'dancevincent',                   # Name = Vincent Dance
'dancewoo',                       # Name = WOO
'danceluigi',                     # Name = Fist Pumpin'
'dancecowboy',                    # Name = The Cowboy
'dancebird',                      # Name = BIRD BIRD BIRD
'dancearmspin',                   # Name = Helicopter Arms
'danceheadspin',                  # Name = Head Spin
'dancemash',                      # Name = Monster Mash
'dimmadome',                      # Name = Mile-High Top Hat
'hammerman',                      # Name = Hammerhead
'beehive',                        # Name = Beehive
'banana',                         # Name = Banana Suit
'scoobis',                        # Name = Scoobis
'hotdogsuit',                     # Name = Hotdog Suit
'squid',                          # Name = Sea Friend
'cc',                             # Name = Familiar Head
'gumshoe',                        # Name = Gumshoe
'tinytophat',                     # Name = Itsy-Bitsy Top Hat
'biggerhead',                     # Name = Bigger Head
'bighead',                        # Name = Big Head
'teapot',                         # Name = Teapot
'spaceshades',                    # Name = Space Shades
'kingcrown',                      # Name = King's Crown
'queencrown',                     # Name = Queen's Crown
'outline',                        # Name = Black Outline
'smokestack',                     # Name = Industrial Hat
'mailbox',                        # Name = Mailbox
'fedora2',                        # Name = Criminal Business
'hearthead',                      # Name = Beaming with Love
'cardtophat',                     # Name = Ace of Hearts
'bubblebee',                      # Name = Bubble Bee Man
'dominus',                        # Name = Dominus Empyreus
'dimmadome2',                     # Name = poo
'kebabulonhead',                  # Name = Kebabulon Head
'vanitybase',                     # Name = VanityBase
'viking',                         # Name = Viking Hat
'headphones',                     # Name = Headphones
'scarf',                          # Name = Scarf
'mohawk',                         # Name = Mohawk
'1hat',                           # Name = #1 Hat
'cowboy',                         # Name = 10 Gallon Hat
'plant',                          # Name = Potted Plant
'bard',                           # Name = Bard Hat
'duckbill',                       # Name = Duck Bill
'partyhatbl',                     # Name = Blue Party Hat
'stupid',                         # Name = Stupid Hat
'cone',                           # Name = Cone
'backwards',                      # Name = Backwards Cap
'beanie',                         # Name = Beanie
'night',                          # Name = Night Vision Goggles
'shades',                         # Name = Cool Shades
'dog',                            # Name = Dog
'glasses',                        # Name = Glasses
'headjar',                        # Name = Head In A Jar
'mcquackers',                     # Name = McQuackers
'knighthelmet',                   # Name = Knight Helmet
'bombboy',                        # Name = Bomb-Boy
'blackknight',                    # Name = Black Knight
'tinpot',                         # Name = Tin Pot
'funnymask',                      # Name = Funny Mask
'partyhatgr',                     # Name = Green Party Hat
'cavernrat',                      # Name = Cavern Rat
'penguin',                        # Name = Penguin
'princecrown',                    # Name = Princely Crown
'tikimask',                       # Name = Teekee Mask
'robotcap',                       # Name = Robot Cap
'pumpkinhat',                     # Name = Pumpking's Pumpkin
'snorkel',                        # Name = Snorkel
'halo',                           # Name = Halo
'trashman',                       # Name = Trash Can
'mop',                            # Name = Mop
'snobaby',                        # Name = Snobaby
'cubeshades',                     # Name = Cubular Shades
'witchhat',                       # Name = Witch Hat
'astronauthelm',                  # Name = Astronaut Helmet
'boppers',                        # Name = Red Boppers
'rubyshades',                     # Name = Ruby Shades
'gamers',                         # Name = Gamer Headset
'devil',                          # Name = Horns
'clownnose',                      # Name = Clown Nose
'cathat',                         # Name = Cat-Eared Hat
'wizhat',                         # Name = Wiz Hat
'gamerpack',                      # Name = Gamer Pack
'phonograph',                     # Name = Phonograph
'disguise',                       # Name = Clever Disguise
'rainbow',                        # Name = Rainbow
'steampunk',                      # Name = Steampunk Goggles
'unicorn',                        # Name = Unicorn Horn
'ribbon',                         # Name = Hair Ribbon
'barrel',                         # Name = Barrel
'fool',                           # Name = Fool's Hat
'liar',                           # Name = Liar's Nose
'bluebeanie',                     # Name = Blue Beanie
'arrowhead',                      # Name = Arrow
'umbrella',                       # Name = Beverage Umbrella
'blackbeanie',                    # Name = Black Beanie
'chefhat',                        # Name = Chef Hat
'anglerfish',                     # Name = Angler Fish
'planetrings',                    # Name = Planetary Rings
'sailor',                         # Name = Sailor Hat
'redbeanie',                      # Name = Red Beanie
'santahat',                       # Name = Stocking Hat
'bluefirehead',                   # Name = Blue Fire
'headband',                       # Name = Headband
'propellercap',                   # Name = Propeller Cap
'partyhatrd',                     # Name = Red Party Hat
'paperbag',                       # Name = Paper Bag
'partyhatyl',                     # Name = Yellow Party Hat
'froggy',                         # Name = Froggy
'rainingtacos',                   # Name = 142376088
'tophat',                         # Name = Tophat
'beebhat',                        # Name = Old Baseball Cap
'spikehelmet',                    # Name = Spiked Helmet
'wizard',                         # Name = 3-Star Wizard
'cadet',                          # Name = Cadet Cap
'swirlyglasses',                  # Name = Swirly Glasses
'rabgirl',                        # Name = Rabgirl
'rabboyhat',                      # Name = Rabboy
'candyshades',                    # Name = Cotton Candy Shades
'strawhat',                       # Name = Straw Hat
'bigstrawhat',                    # Name = Big Straw Hat
'aviator',                        # Name = Aviator Helmet
'redegg',                         # Name = Red Egg
'bowler',                         # Name = Bowler
'booger',                         # Name = Common Cold
'hatchling',                      # Name = Hatchling
'eyeball',                        # Name = Eyeball
'eggstick',                       # Name = Eggstick
'eyepoppers',                     # Name = Eye Poppers
'gmushroom',                      # Name = Green Mushroom
'candles',                        # Name = Candles
'duckie',                         # Name = Duckie
'bread',                          # Name = Bread
'wichhat',                        # Name = Wich Hat
'snowman',                        # Name = Snowman Head
'cape',                           # Name = Cape
'chikhood',                       # Name = Chicklet Hood
'fancyglasses',                   # Name = Designer Frames
'mushmount',                      # Name = Mushroom Servant
'skelmet',                        # Name = Skelmet
'friendhelmet',                   # Name = Hyper-realistic Friend
'antennae2',                      # Name = Alien Antennae
'antennae',                       # Name = Antennae
'bombyhat',                       # Name = Mr. Bomby
'macaroni',                       # Name = Macaroni Art
'tvhead',                         # Name = Old TV
'dizzy',                          # Name = Dizzy Stars
'baubleman',                      # Name = Bauble Head
'unibrow',                        # Name = Threatening Unibrow
'hardhat',                        # Name = Hard Hat
'antlers',                        # Name = Reindeer Antlers
'wormstring',                     # Name = Worm On A String
'pizzasuit',                      # Name = Pizza Suit
'80sglasses',                     # Name = Funky 80s Shades
'dino2mask',                      # Name = Minisaurus Rox Mask
'dinomask',                       # Name = Dinosaurus Rox Mask
'partyhatpr',                     # Name = Purple Party Hat
'brain',                          # Name = Brain
'baubleman2',                     # Name = Green Bauble Head
'chungy',                         # Name = Carrot
'siren',                          # Name = Robot's Siren
'pearlbracelet',                  # Name = Pearl Bracelets
'sunflowerbarrette',              # Name = Sunflower Barrette
'bangles',                        # Name = Bangles
'lovedolphins',                   # Name = I <3 Dolphins
'sillyhat',                       # Name = Silly Top Hat
'heartshades',                    # Name = Heart Shades
'loveantennae',                   # Name = Heart Antennae
'fedora',                         # Name = Fedora
'hatkid',                         # Name = Alien's Top Hat
'police',                         # Name = Police Cap
'dunce',                          # Name = P1tty's Dunce Hat
'skinbase',                       # Name = SkinBase
'whitegold',                      # Name = Yellow Outfit
'magicskin',                      # Name = Magic Skin
'tux',                            # Name = Gag Tux
'wizardrobes',                    # Name = Wizard Robes
'redjacket',                      # Name = Red Jacket
'ceo',                            # Name = CEO Uniform
'cowboyskin',                     # Name = Cowboy Outfit
'cube',                           # Name = Familiar Clothes
'janitor',                        # Name = Janitor Uniform
'todd',                           # Name = Turnip Suit
'scuba',                          # Name = Scuba Gear
'tanktop',                        # Name = Tank Top
'ouch',                           # Name = Ouch!
'jacket',                         # Name = Leather Jacket
'green',                          # Name = Green Outfit
'red',                            # Name = Red Outfit
'loner',                          # Name = Loner Outfit
'whitecollar',                    # Name = Employee Uniform
'parker',                         # Name = Parker's Outfit
'racer',                          # Name = Racer Suit
'silverskin',                     # Name = Silver Skin
'cubehoodie',                     # Name = Cube Hoodie
'rabboy',                         # Name = Rabboy Suit
'bryantclothes',                  # Name = Bryant's Clothes
'soccer',                         # Name = Soccer Jersey
'redvarsity',                     # Name = Red Varsity
'tourist',                        # Name = Tourist
'hipster',                        # Name = Hipster
'dinotee',                        # Name = Dino Tee
'shrooms',                        # Name = Mushroom Kid
'scientist',                      # Name = Scientist
'beans',                          # Name = Gimme Beans Shirt
'correct',                        # Name = Correct Shirt
'beebo',                          # Name = Beebo's Outfit
'catsweater',                     # Name = Cat Sweater
'candy',                          # Name = Candy Suit
'farmer',                         # Name = Farmer's Overalls
'viptshirt',                      # Name = VIP T-Shirt
'punk',                           # Name = Punker Vest
'roland',                         # Name = Roland's Outfit
'bribbleshirt',                   # Name = BRIBBLECO Enthusiast
'familyman',                      # Name = Father's Clothes
'bloxxer',                        # Name = Nostalgic Tee
'ddd',                            # Name = Royal Penguin
'prison',                         # Name = Prisoner
'saturn',                         # Name = Saturn Kid
'pride',                          # Name = Prideful Sweater
'clown',                          # Name = Clown Outfit
'scout',                          # Name = Cavern Scout
'chef',                           # Name = Chef Uniform
'robotthing',                     # Name = Robot 64 Shirt
'norobot',                        # Name = No Stinky Robots!
'yellopjs',                       # Name = Yellow Enemy Pajamas
'greenscreen',                    # Name = Greenscreen Bodysuit
'kebabulon',                      # Name = Kebabulonian
'dave',                           # Name = Dave's Clothes
'snoday',                         # Name = Sno Day Shirt
'weezard',                        # Name = Weezard
'coolkid',                        # Name = Cool Kid
'crybaby',                        # Name = Crybaby
'pajamas',                        # Name = Pajamas
'floweroveralls',                 # Name = Flower Overalls
'fancyshirt',                     # Name = Fancy Shirt
'graphicpjs',                     # Name = Graphic PJs
'constructionvest',               # Name = Construction Vest
'flameboyfan',                    # Name = Flame Boy Fan
'fieri',                          # Name = Fiery Polo
'chauffeur',                      # Name = Chauffeur
'glassskin',                      # Name = Glass Skin
'blueskin',                       # Name = Mycelium Suit
'iloveyou',                       # Name = Affectionate Shirt
'artist',                         # Name = Artist's Apron
'sailor2',                        # Name = Sailor Uniform
'eighties',                       # Name = Neon Tracksuit
'oddport',                        # Name = Odd Transfer Student
'mummy',                          # Name = Mummy Wrap
'lonk',                           # Name = Adventurer's Tunic
'sourshirt',                      # Name = Sour Shirt
'snocoat',                        # Name = Snowy Coat
'antiskin',                       # Name = Antiskin
'pumpkinstudent',                 # Name = Pumpkin Student
'vincent',                        # Name = Vincent's Work Wear
'nigel',                          # Name = Nigel's Sweater
'mushrider',                      # Name = Mushroom Rider
'waluigi',                        # Name = Purple Overalls
'oddportV2',                      # Name = Odd Transfer Student
'fishies',                        # Name = Fishy Fashion
'pirate',                         # Name = Pirate Captain
'flowershirt',                    # Name = Smiley Flower
'bombyfan',                       # Name = I <3 Bomby Shirt
'cropcoat',                       # Name = Cropped Coat
'motorcyleshirt',                 # Name = Motorcycle Shirt
'scoutfit',                       # Name = Runner's Casual
'igotoverit',                     # Name = Victory Tee
'societyman',                     # Name = Funky Suit
'womensclothes',                  # Name = Popular Women's Clothing
'cottoncandyshirt',               # Name = Fresh Sweater
'friendship',                     # Name = Friendship Tee
'funnybelle',                     # Name = Secretary's Outfit
'crophoodie',                     # Name = Tied Crop Jacket
'doctorshirt',                    # Name = Doctor
'jeanjacket',                     # Name = Jean Jacket
'zkevin',                         # Name = Pizza Boy
'bowkid',                         # Name = Sidekick's Outfit
'rabgirlskin',                    # Name = Rabgirl Suit
'babyboy',                        # Name = Baby Boy Outfit
'ufosroutfit',                    # Name = Alien's Getup
'lovetux',                        # Name = Lovely Tuxedo
'lovedress',                      # Name = Lovely Dress
'verbalase',                      # Name = Beatboxer's Outfit
'jeandress',                      # Name = Jean Dress
'slimeskin',                      # Name = Slime Skin
'scarfjacket',                    # Name = Scarf Jacket
'chikhoodie',                     # Name = Chicklet Hoodie
'superclown',                     # Name = Silly Tuxedo
'buttonup',                       # Name = Motherly Button-Up
'funnyjacket',                    # Name = Blue Jacket
'lucas',                          # Name = Boy From Nowhere
'joker',                          # Name = Estate Agent’s Outfit
'bigsmoke',                       # Name = Smoky Outfit
'dougoutfit',                     # Name = Mile-High Suit
'diner',                          # Name = Diner Uniform
'orangehood',                     # Name = Orange Hoodie
'eddie',                          # Name = Eddie’s Workwear
'froggysweater',                  # Name = Froggy Sweater
'jimmyneutron',                   # Name = Jimmy Neutron
'banjo',                          # Name = Beige Coat
'varsity',                        # Name = Varsity Jacket
'inkling',                        # Name = Squid Kid
'miku',                           # Name = Pop Star's Getup
'blueboss',                       # Name = Smelly Pirate Outfit
'beefit',                         # Name = Bumbling Idiot
'maid',                           # Name = Maid Outfit
'spacecaptain',                   # Name = Space Pirate Captain
'swagshirt',                      # Name = Swag Shirt
'soos',                           # Name = Outfit of Mystery
'drip',                           # Name = Cursed Outfit
'swegter',                        # Name = Swegter
'investigator',                   # Name = The Investigator
'suponjibobu',                    # Name = Fry Cook
'ilovesticky',                    # Name = I <3 Sticky
'skelebones',                     # Name = Skelebones
'winner',                         # Name = L Shirt
'departmentstore',                # Name = Department Store Apron
'shaggy',                         # Name = Dog Lover's Outfit
'bubsy',                          # Name = Wrongful Shirt
'yumenikki',                      # Name = Sweater of Dreams
'liza',                           # Name = Swimmer's Casual
'omori',                          # Name = Shut-in's Wear
'bluehoodie',                     # Name = Blue Hoodie
'timmy',                          # Name = Ungrateful Godchild
'sheldon',                        # Name = Stylish Ripoff
'template',                       # Name = Template Skin
}